name: Code Review

on: [push, pull_request]

jobs:
  php:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-18.04, windows-2019 ]
        php: [ '7.2', '7.3', '7.4' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }} environment
        uses: nanasess/setup-php@v3.0.6
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Caching Composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Linting PHP Coding Standard
        run: composer cs:lint

      - name: Linting Rector improvements
        if: matrix.php != '7.2'
        run: composer refactor:lint
