name: Code Review

on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-20.04

    strategy:
      max-parallel: 2
      matrix:
        php: ['7.4', '7.3', '7.2']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }} environment
        uses: nanasess/setup-php@v3.0.6
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Caching Composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Linting PHP Coding Standard
        run: composer cs:lint

      - name: Linting Rector improvements
        run: composer refactor:lint
